version: "3"
# containers are spceified as services
services:

  nginx:
    ports:
      - 80:80
  # below we will add configs that are specific to node-app container
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
      environment:
        - NODE_ENV=production
        - SESSION_SECRET=${SESSION_SECRET}

    command: [ "/bin/sh", "-c", "npm run build;npm start" ]

  mongo-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
